import {useEffect,useMemo,useRef,useState} from "react";
import {Link,NavLink,Route,Routes,useNavigate,useParams} from "react-router-dom";

const LANG={es:"ES",en:"EN",sv:"SV",de:"DE",fr:"FR"};
const TXT={
es:{explore:"Explorar",create:"Crear",developer:"Developer",account:"Cuenta",login:"Iniciar sesión",register:"Crear cuenta",logout:"Cerrar sesión",delete:"Borrar cuenta",publish:"Publicar",save:"Guardar",missions:"Misiones",wallet:"F¢",settings:"Ajustes",projects:"Proyectos",play:"Jugar",like:"Me gusta",back:"Volver",objects:"OBJETOS",properties:"PROPIEDADES",search:"Buscar juegos…",newGame:"Nuevo juego"},
en:{explore:"Explore",create:"Create",developer:"Developer",account:"Account",login:"Log in",register:"Create account",logout:"Log out",delete:"Delete account",publish:"Publish",save:"Save",missions:"Missions",wallet:"F¢",settings:"Settings",projects:"Projects",play:"Play",like:"Like",back:"Back",objects:"OBJECTS",properties:"PROPERTIES",search:"Search games…",newGame:"New game"},
sv:{explore:"Utforska",create:"Skapa",developer:"Utvecklare",account:"Konto",login:"Logga in",register:"Skapa konto",logout:"Logga ut",delete:"Ta bort konto",publish:"Publicera",save:"Spara",missions:"Uppdrag",wallet:"F¢",settings:"Inställningar",projects:"Projekt",play:"Spela",like:"Gilla",back:"Tillbaka",objects:"OBJEKT",properties:"EGENSKAPER",search:"Sök spel…",newGame:"Nytt spel"},
de:{explore:"Entdecken",create:"Erstellen",developer:"Entwickler",account:"Konto",login:"Anmelden",register:"Konto erstellen",logout:"Abmelden",delete:"Konto löschen",publish:"Veröffentlichen",save:"Speichern",missions:"Missionen",wallet:"F¢",settings:"Einstellungen",projects:"Projekte",play:"Spielen",like:"Gefällt mir",back:"Zurück",objects:"OBJEKTE",properties:"EIGENSCHAFTEN",search:"Spiele suchen…",newGame:"Neues Spiel"},
fr:{explore:"Explorer",create:"Créer",developer:"Développeur",account:"Compte",login:"Connexion",register:"Créer un compte",logout:"Déconnexion",delete:"Supprimer le compte",publish:"Publier",save:"Enregistrer",missions:"Missions",wallet:"F¢",settings:"Réglages",projects:"Projets",play:"Jouer",like:"J'aime",back:"Retour",objects:"OBJETS",properties:"PROPRIÉTÉS",search:"Rechercher des jeux…",newGame:"Nouveau jeu"}};
const seed=[];
const reserved=["keplerians","roblox corporation","dvloper","granny","evil nun","ice scream","mr meat","datavaseloper"];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

function useLang(){const[lang,setLang]=useState(()=>localStorage.getItem("eskadin-lang")||"es");useEffect(()=>localStorage.setItem("eskadin-lang",lang),[lang]);return[lang,TXT[lang]]}
function useUser(){const[user,setUser]=useState(()=>read("eskadin-user",null));return{user,login:u=>{setUser(u);save("eskadin-user",u)},logout:()=>{setUser(null);localStorage.removeItem("eskadin-user")}}}
function useGames(){const[games,setGames]=useState(()=>read("eskadin-games",seed));useEffect(()=>save("eskadin-games",games),[games]);return[games,setGames]}

function Shell({children}){const[lang,setLang]=useLang();const t=TXT[lang];const{user}=useUser();return <div className="app-shell"><div className="wrap"><nav className="nav"><Link className="brand" to="/">Esk<span>å</span>din St<span>ü</span>dis<sup>®</sup></Link><div className="nav-links"><NavLink to="/games">{t.explore}</NavLink><NavLink to="/editor">{t.create}</NavLink><NavLink to="/missions">{t.missions}</NavLink><NavLink to="/developer">{t.developer}</NavLink></div><div className="nav-actions"><select className="lang" value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(LANG).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{user?<Link className="avatar-link" to="/account">{user.name.slice(0,2).toUpperCase()}</Link>:<Link className="button button-primary small" to="/login">{t.login}</Link>}</div></nav>{children}<footer className="footer"><span>© 2026 Eskådin Stüdis®</span><span>0 ads · 0 real-money purchases · F¢ gameplay-only</span></footer></div></div>}

function Home(){const[,t]=useLang();return <main><section className="hero"><div className="hero-grid"><div className="hero-copy"><div className="pill">ESKÅDIN STÜDIS® · CREATOR PLATFORM</div><h1><span>{t.create}.</span><span className="gradient">{t.publish}.</span><span>{t.play}.</span></h1><p className="lead">Create 3D experiences, publish them and play them without ads or real-money purchases.</p><div className="actions"><Link className="button button-primary" to="/editor">{t.create}</Link><Link className="button button-ghost" to="/games">{t.explore}</Link></div></div><div className="hero-device"><div className="device-top"><b>eskadin://studio</b><span>LIVE</span></div><div className="device-scene"><div className="scene-orb"/><div className="scene-building"/><div className="scene-floor"/></div><div className="device-bottom"><span>SCENE</span><span>OBJECTS · 4</span><span>PREVIEW</span></div></div></div></section><section className="section"><div className="section-head"><div className="eyebrow">STUDIO</div><h2>A small creator platform that actually does things.</h2><p>Editor, projects, publishing, profiles, F¢ missions, analytics and playable previews.</p></div><div className="feature-grid"><article className="card"><div className="icon">01</div><h3>Scene editor</h3><p>Objects, hierarchy, transforms, duplicate, delete, save and preview.</p></article><article className="card"><div className="icon">02</div><h3>Community</h3><p>Publish experiences, browse games, like them and play them.</p></article><article className="card"><div className="icon">03</div><h3>F¢ economy</h3><p>Earn platform currency through missions. Never buy it with real money.</p></article></div></section></main>}

function Games(){const[,t]=useLang();const[games]=useGames();const[q,setQ]=useState("");const filtered=useMemo(()=>games.filter(g=>(g.title+" "+g.genre+" "+g.author).toLowerCase().includes(q.toLowerCase())),[games,q]);return <main className="page"><div className="page-head"><div><div className="eyebrow">{t.explore}</div><h1 className="page-title">Community games</h1></div><Link className="button button-primary" to="/editor">{t.newGame}</Link></div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search}/></div><div className="games-grid">{filtered.map(g=><Link className="game-card" to={"/games/"+g.id} key={g.id}><div className={"game-cover "+g.color}><span>{g.tag}</span></div><div className="game-info"><h3>{g.title}</h3><p>{g.genre} · {g.author}</p><b>♥ {g.likes.toLocaleString()} · {g.players.toLocaleString()} online</b></div></Link>)}</div></main>}

function Game(){const[,t]=useLang();const{id}=useParams();const[games]=useGames();const game=games.find(g=>String(g.id)===id)||games[0];const[liked,setLiked]=useState(false);return <main className="page"><Link className="back" to="/games">← {t.back}</Link><div className="game-hero"><div className={"game-cover big "+game.color}><span>{game.title}</span></div><div><div className="eyebrow">{game.tag} · {game.author}</div><h1 className="page-title">{game.title}</h1><p>{game.description}</p><p className="muted">{game.genre} · {game.players.toLocaleString()} playing · {(game.likes+(liked?1:0)).toLocaleString()} likes</p><div className="actions"><Link className="button button-primary" to={"/games/"+game.id+"/play"}>▶ {t.play}</Link><button className="button button-ghost" onClick={()=>setLiked(!liked)}>{liked?"♥":"♡"} {liked?"Liked":t.like}</button></div></div></div></main>}

function Play(){const[,t]=useLang();const{id}=useParams();const[games]=useGames();const game=games.find(g=>String(g.id)===id)||games[0];const[started,setStarted]=useState(false);return <main className="page play"><div className="playbar"><Link to={"/games/"+game.id}>← {t.back}</Link><b>{game.title}</b><span>{started?"LIVE":"READY"}</span></div><div className="game-viewport">{started?<div className="play-message"><strong>ESKÅDIN RUNTIME</strong><small>Scene loaded · session active</small></div>:<div className="launch-card"><span>PLAYABLE PREVIEW</span><h2>{game.title}</h2><p>{game.description}</p><button className="button button-primary" onClick={()=>setStarted(true)}>▶ {t.play}</button></div>}</div></main>}

const sceneSeed=[{id:1,type:"wall",name:"Wall 01",x:0,y:0,z:0,rx:0,ry:0,rz:0,s:1},{id:2,type:"cube",name:"Cube 02",x:2,y:0,z:0,rx:0,ry:0,rz:0,s:1},{id:3,type:"light",name:"Light 03",x:0,y:3,z:2,rx:0,ry:0,rz:0,s:1}];
function Editor(){const[,t]=useLang();const[scene,setScene]=useState(()=>read("eskadin-scene",sceneSeed));const[selected,setSelected]=useState(1);const[tool,setTool]=useState("select");const[saved,setSaved]=useState(false);const[grid,setGrid]=useState(true);const[drag,setDrag]=useState(null);const canvasRef=useRef(null);const obj=scene.find(o=>o.id===selected);
const upd=(id,patch)=>setScene(s=>s.map(o=>o.id===id?{...o,...patch}:o));
const add=type=>{const id=Date.now();setScene(s=>[...s,{id,type,name:type+" "+(s.length+1),x:0,y:0,z:0,rx:0,ry:0,rz:0,s:1}]);setSelected(id)};
const saveScene=()=>{save("eskadin-scene",scene);setSaved(true);setTimeout(()=>setSaved(false),1000)};
const del=()=>{setScene(s=>s.filter(o=>o.id!==selected));setSelected(null)};
const dup=()=>obj&&setScene(s=>[...s,{...obj,id:Date.now(),name:obj.name+" copy",x:obj.x+.5,z:obj.z+.5}]);
const pointerDown=e=>{if(!obj||tool!=="select")return;e.currentTarget.setPointerCapture?.(e.pointerId);setDrag({id:obj.id,x:e.clientX,y:e.clientY,ox:obj.x,oz:obj.z})};
const pointerMove=e=>{if(!drag)return;const dx=(e.clientX-drag.x)/35,dz=(e.clientY-drag.y)/35;upd(drag.id,{x:Math.round((drag.ox+dx)*10)/10,z:Math.round((drag.oz+dz)*10)/10})};
const pointerUp=()=>setDrag(null);
return <main className="page editor-page"><div className="page-head"><div><div className="eyebrow">ESKÅDIN CREATOR · 3D</div><h1 className="page-title">{t.create}</h1><p>Touch, mouse and pointer controls. The scene is an actual editable 3D-style workspace.</p></div><div className="actions"><button className="button button-ghost" onClick={saveScene}>{saved?"✓ "+t.save:t.save}</button><Link className="button button-primary" to="/publish">{t.publish}</Link></div></div>
<div className="editor-toolbar"><button className={tool==="select"?"active":""} onClick={()=>setTool("select")}>↖ Select</button><button className={tool==="move"?"active":""} onClick={()=>setTool("move")}>✥ Move</button><button className={tool==="rotate"?"active":""} onClick={()=>setTool("rotate")}>↻ Rotate</button><button className={tool==="scale"?"active":""} onClick={()=>setTool("scale")}>⤢ Scale</button><span className="tool-spacer"/><button onClick={()=>setGrid(!grid)}>{grid?"▦ Grid":"□ Grid"}</button><button onClick={dup}>＋ Duplicate</button><button onClick={del}>⌫ Delete</button><button onClick={()=>setScene(sceneSeed)}>↺ Reset</button></div>
<div className="editor-layout"><aside className="editor-side"><b>{t.objects}</b>{["wall","cube","light","sound","spawn","camera","text"].map(type=><button key={type} onClick={()=>add(type)}>＋ {type}</button>)}<div className="object-list">{scene.map(o=><button className={o.id===selected?"selected":""} onClick={()=>setSelected(o.id)} key={o.id}>{o.name}</button>)}</div></aside>
<div className={"editor-canvas real3d "+(grid?"with-grid":"")} ref={canvasRef} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><div className="viewport-hud"><span>3D VIEWPORT</span><span>drag = X/Z</span></div><div className="axis axis-x"/><div className="axis axis-z"/>{scene.map(o=><button key={o.id} className={"scene-object3d "+o.type+(o.id===selected?" selected":"")} style={{left:"calc(50% + "+(o.x*38)+"px)",top:"calc(50% - "+(o.z*38-o.y*25)+"px)",transform:"translate(-50%,-50%) rotate("+o.ry+"deg) scale("+o.s+")"}} onPointerDown={e=>{setSelected(o.id);pointerDown(e)}}>{o.type==="text"?"T":o.type==="light"?"◉":o.type==="camera"?"▱":o.type==="spawn"?"⌁":"◆"}<small>{o.name}</small></button>)}</div>
<aside className="properties"><b>{t.properties}</b>{obj?<><label>Name<input value={obj.name} onChange={e=>upd(obj.id,{name:e.target.value})}/></label><div className="xyz"><label>X<input type="number" step=".1" value={obj.x} onChange={e=>upd(obj.id,{x:Number(e.target.value)})}/></label><label>Y<input type="number" step=".1" value={obj.y} onChange={e=>upd(obj.id,{y:Number(e.target.value)})}/></label><label>Z<input type="number" step=".1" value={obj.z} onChange={e=>upd(obj.id,{z:Number(e.target.value)})}/></label></div><div className="xyz"><label>RX<input type="number" value={obj.rx} onChange={e=>upd(obj.id,{rx:Number(e.target.value)})}/></label><label>RY<input type="number" value={obj.ry} onChange={e=>upd(obj.id,{ry:Number(e.target.value)})}/></label><label>RZ<input type="number" value={obj.rz} onChange={e=>upd(obj.id,{rz:Number(e.target.value)})}/></label></div><label>Scale<input type="number" step=".1" min=".1" value={obj.s} onChange={e=>upd(obj.id,{s:Number(e.target.value)})}/></label></>:<span className="muted">Select an object.</span>}</aside></div><div className="editor-bottom"><Link className="button button-ghost" to="/games/1/play">{t.play}</Link><span>{scene.length} objects · touch/mouse editing · saved locally</span></div></main>}
function Developer(){const[,t]=useLang();return <main className="page"><div className="eyebrow">{t.developer}</div><h1 className="page-title">Your studio.</h1><div className="dashboard-grid"><Link to="/editor" className="dash"><b>🧱 {t.create}</b><span>Build and preview.</span></Link><Link to="/projects" className="dash"><b>🗂 {t.projects}</b><span>Manage projects.</span></Link><Link to="/publish" className="dash"><b>📤 {t.publish}</b><span>Release a game.</span></Link><Link to="/statistics" className="dash"><b>📊 Statistics</b><span>Visits, likes and sessions.</span></Link></div></main>}

function Publish(){const[,t]=useLang();const[games,setGames]=useGames();const{user}=useUser();const[name,setName]=useState("My new game");const[desc,setDesc]=useState("A new Eskådin Stüdis experience.");const[done,setDone]=useState(false);const blocked=reserved.some(x=>name.toLowerCase().replace(/[^a-z0-9 ]/g,"").includes(x.replace(/[^a-z0-9 ]/g,"")));const go=()=>{if(blocked)return;setGames(g=>[...g,{id:Date.now(),title:name,genre:"3D Experience",tag:"New",color:"violet",players:0,likes:0,author:user?.name||"Eskådin Creator",description:desc}]);setDone(true)};return <main className="page narrow"><div className="eyebrow">{t.publish}</div><h1 className="page-title">{done?t.published:t.publish}</h1>{done?<div className="success-card"><b>✓ {t.publish}</b><p>Your game is now in the local catalog.</p><Link className="button button-primary" to="/games">{t.explore}</Link></div>:<div className="form-card"><label>{t.name}<input value={name} onChange={e=>setName(e.target.value)}/></label>{blocked&&<p className="error">Reserved developer or game name.</p>}<label>{t.description}<textarea value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Visibility<select><option>Public</option><option>Private</option></select></label><button className="button button-primary" disabled={blocked} onClick={go}>{t.publish} · 0€</button><p className="muted">Real-money payments are blocked. F¢ cannot be purchased or withdrawn.</p></div>}</main>}

function Missions(){const[,t]=useLang();const[balance,setBalance]=useState(()=>Number(localStorage.getItem("eskadin-fc")||0));const[claimed,setClaimed]=useState(()=>read("eskadin-missions",{}));const ms=[["play","Play a new experience",8],["explore","Explore a creator",12],["like","Like an experience",5]];const claim=(id,n)=>{if(claimed[id])return;const next=balance+n;setBalance(next);localStorage.setItem("eskadin-fc",String(next));const c={...claimed,[id]:true};setClaimed(c);save("eskadin-missions",c)};return <main className="page"><div className="eyebrow">{t.missions}</div><h1 className="page-title">F¢ missions</h1><div className="wallet-banner"><b>{balance} F¢</b><span>Earn platform currency by playing.</span><Link to="/wallet">{t.wallet}</Link></div><div className="mission-grid">{ms.map(([id,title,n])=><div className="mission-card" key={id}><span>MISSION</span><h3>{title}</h3><strong>+{n} F¢</strong><button className="button button-primary" disabled={!!claimed[id]} onClick={()=>claim(id,n)}>{claimed[id]?"✓ Claimed":"Claim"}</button></div>)}</div></main>}

function Wallet(){const[,t]=useLang();const balance=Number(localStorage.getItem("eskadin-fc")||0);return <main className="page narrow"><div className="eyebrow">{t.wallet}</div><h1 className="page-title">{balance} F¢</h1><div className="form-card"><h2>Platform currency</h2><p className="muted">F¢ can only be earned through platform gameplay missions. It cannot be purchased, withdrawn or converted to real money.</p><Link className="button button-primary" to="/missions">{t.missions}</Link></div></main>}

function Projects(){return <main className="page"><div className="eyebrow">PROJECTS</div><h1 className="page-title">Your projects.</h1><div className="dashboard-grid"><Link className="dash" to="/editor"><b>Neon prototype</b><span>Local editable scene</span></Link><Link className="dash" to="/editor"><b>Untitled project</b><span>Draft scene</span></Link></div></main>}

function Statistics(){return <main className="page"><div className="eyebrow">ANALYTICS</div><h1 className="page-title">Studio analytics.</h1><div className="stats-grid"><div><b>12.4K</b><span>Visits</span></div><div><b>1.8K</b><span>Likes</span></div><div><b>3.2K</b><span>Sessions</span></div><div><b>48h</b><span>Playtime</span></div></div><div className="chart"><span className="chart-title">Weekly activity</span>{[42,61,48,78,69,92,74].map((h,i)=><i style={{height:h+"%"}} key={i}/>)}</div></main>}

function Account(){const[,t]=useLang();const{user,logout}=useUser();return <main className="page narrow"><div className="eyebrow">{t.account}</div><h1 className="page-title">{user?.name||"Eskådin Player"}</h1><div className="form-card"><div className="account-avatar">{(user?.name||"ES").slice(0,2).toUpperCase()}</div><p className="muted">0 published games · 0 sessions · {Number(localStorage.getItem("eskadin-fc")||0)} F¢</p><div className="account-actions"><Link className="button button-ghost" to="/editor">{t.create}</Link><Link className="button button-ghost" to="/wallet">{t.wallet}</Link><Link className="button button-ghost" to="/settings">{t.settings}</Link><Link className="button danger-button" to="/account/delete">{t.delete}</Link></div><button className="button button-ghost" onClick={logout}>{t.logout}</button></div></main>}

function Settings(){const[lang,setLang]=useLang();const t=TXT[lang];return <main className="page narrow"><div className="eyebrow">{t.settings}</div><h1 className="page-title">{t.settings}</h1><div className="form-card"><label>{t.language}<select value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(LANG).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p className="muted">Language is stored locally on this device.</p></div></main>}

function Login(){const[,t]=useLang();const{login}=useUser();const nav=useNavigate();const[name,setName]=useState("");return <main className="page narrow auth-page"><div className="form-card auth-card"><div className="eyebrow">{t.account}</div><h1>{t.login}</h1><label>Email<input type="email"/></label><label>Password<input type="password"/></label><label>Display name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><button className="button button-primary" onClick={()=>{login({name:name||"Eskådin Player"});nav("/account")}}>{t.login}</button><Link className="muted" to="/register">{t.register}</Link></div></main>}

function Register(){const[,t]=useLang();const{login}=useUser();const nav=useNavigate();const[name,setName]=useState("");return <main className="page narrow auth-page"><div className="form-card auth-card"><div className="eyebrow">{t.account}</div><h1>{t.register}</h1><label>Username<input value={name} onChange={e=>setName(e.target.value)} placeholder="Creator name"/></label><label>Email<input type="email"/></label><label>Password<input type="password"/></label><label>Confirm password<input type="password"/></label><button className="button button-primary" onClick={()=>{login({name:name||"Eskådin Creator"});nav("/account")}}>{t.register}</button><Link className="muted" to="/login">{t.login}</Link></div></main>}

function DeleteAccount(){const[,t]=useLang();const{logout}=useUser();const nav=useNavigate();const[c,setC]=useState("");return <main className="page narrow auth-page"><div className="form-card danger-card"><div className="eyebrow danger">DANGER ZONE</div><h1>{t.delete}</h1><p className="muted">This clears the local account and session on this device.</p><input value={c} onChange={e=>setC(e.target.value)} placeholder="DELETE"/><button className="button danger-button" disabled={c!=="DELETE"} onClick={()=>{logout();localStorage.removeItem("eskadin-fc");nav("/")}}>{t.delete}</button></div></main>}

function NotFound(){return <main className="page notfound"><h1>404</h1><p>This page escaped the editor.</p><Link className="button button-primary" to="/">Home</Link></main>}

export default function CompleteApp(){return <Shell><Routes><Route path="/" element={<Home/>}/><Route path="/games" element={<Games/>}/><Route path="/games/:id" element={<Game/>}/><Route path="/games/:id/play" element={<Play/>}/><Route path="/editor" element={<Editor/>}/><Route path="/developer" element={<Developer/>}/><Route path="/projects" element={<Projects/>}/><Route path="/publish" element={<Publish/>}/><Route path="/missions" element={<Missions/>}/><Route path="/wallet" element={<Wallet/>}/><Route path="/statistics" element={<Statistics/>}/><Route path="/account" element={<Account/>}/><Route path="/settings" element={<Settings/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/account/delete" element={<DeleteAccount/>}/><Route path="*" element={<NotFound/>}/></Routes></Shell>}
